### User can get the details of customers who assigned to them
### if user role is admin they can access all customer details
GET http://localhost:3000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzg4OTA3OX0.8MmYC053-WxOQ8N-bd9JdiKo1kvr2kBLt8JgP67gKkg

### Only the user can get access the customer who are assigned to them details
GET http://localhost:3000/customer/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk


### User whose role is admin can access all users data if role is user only get their own details
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDkwODgxN30.SFFtd7ABy0j-SP87bs39vG2vPzIG6dSQ2McWkZGcIAM

### User get access to get customer details who are assigned to them with filtering options
GET http://localhost:3000/customers/?name=Bob&company=xyz&offset=0&limit=3&order_by=id&order=ASC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk

### Register a User
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "anu",
    "email": "anu@example.com",
    "password": "anu123",
    "role": "admin"
}

### Login User
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "anu@example.com",
    "password": "anu123"
}

### User can See their profile details
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk

### Add customer
POST http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk
Content-Type: application/json

{
    "name": "abc",
    "email": "abc@gmail.com",
    "phone": "1234567796",
    "company": "abc",
    "user_id": 12
}

### admin only can update the any customers 
### Only user assign with customer can update customer detail
PUT http://localhost:3000/customer/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk
Content-Type: application/json

{
     "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": "1234567890",
    "company": "Tech Corp",
    "user_id": 12
  }


### User delete only customers who assigned to them 
### Admin has access to delete any customer
DELETE http://localhost:3000/customer/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk

### Admin only can delete users
### And Deleted user customers will automatically assign to other users
DELETE http://localhost:3000/user/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFudUBleGFtcGxlLmNvbSIsImlhdCI6MTczNzczMzY2OX0.mSr5n21rjaylY30MVdtQP0No3Yygx2QkpQHTyPQCcIk
